language: node_js
node_js:
  - "7"
  - "6"

cache: yarn
notifications:
  slack:
    secure: OiH7FIsZyDqdcg/9ijyuC0lhrtI2Liwt5Cps86C9r6T55SVD98c8XU73JdOkc6JkBfI6wtGCqO5jvdQpLn6fXKSLFX0uK+ft7BPQH3Ygj/8kGTiDoHqH3QS2Vhsy5Exb/AQPJcHz62MmhsieqDB8CC/jUrbeMl6AS6MOj8EN6cpsYOJqvBnhexl9ozrJraXaoE7pr3XiflNJYz/fwIya41YFXEHIrkQiCMdhTZlPM81/kZP/UNEALmGIKifJ9gIetJeHEpNqzhWEFHnVMBI++lLWhnzLLyneiOSvecKEK5N83D+PKwx3azdjTW48uU3H8kZkJUaraZ8HuJyCpt8RqlKhoWvpO/DPUjZ6bfwl9Q8/X2aulEuifF0Gp0YQ+e4qkkMRA6jiWFqGpwO4f6uNJC1daT69pz9B7EiZy58H0LmCUcEmBpfixvTeZTFDE7rjQimL+g1sxhFqkGm93tkjYxLk7dgvaHmtSfAhDE49P1bUjclON0P3P/Da8jO8LNlXvYtLDyDtlb1PDDfjRSFA+FZ1hUygz9NxGUy52ReXjC8b7Cdsa81hzZY7fk0SrCroI0O1d0RMpOMvKTX1DbTHNgkQ3YQYtBALUsWU4CHs+aRFMIW2NSldyA0YomK0zg2aDedx6nC353eoRSNvKrI9yMJmLPnDYxrECCuKk1+g3Ws=
